// ─── UI strings — simple Hindi (primary) + English (optional) ───────────────
import type { Language } from './types';

const hi = {
  appName: 'दाली रजिस्टर',
  tagline: 'आपकी शादी की दाली अब आपकी मोबाइल कॉपी में।',
  myRegisters: 'मेरी रजिस्टर',
  people: 'लोग',
  open: 'खोलें',
  newRegister: 'नया रजिस्टर',
  newRegisterTitle: 'नई शादी / नया रजिस्टर',
  createFirst: 'अपना पहला रजिस्टर बनाएँ',
  noEntriesHome: 'अभी कोई रजिस्टर नहीं बना।',
  eventName: 'शादी / कार्यक्रम का नाम',
  eventNamePh: 'जैसे: भाई की शादी',
  location: 'स्थान',
  locationPh: 'गाँव / शहर',
  createRegister: 'रजिस्टर बनाएँ',
  nameNeeded: 'पहले नाम लिखें',

  // notebook
  daaliRegister: 'दाली रजिस्टर',
  eventLabel: 'शादी / कार्यक्रम',
  dateLabel: 'तारीख',
  villageLabel: 'गाँव / स्थान',
  colCr: 'क्र.',
  colName: 'नाम',
  colVillage: 'गाँव / स्थान',
  colRelation: 'रिश्ता',
  colAmount: 'रकम',
  colDate: 'तारीख',
  page: 'पन्ना',
  totalPeople: 'कुल लोग',
  totalDaali: 'कुल दाली',
  pageTotal: 'इस पन्ने में',
  average: 'औसत',
  emptyPage: 'इस पन्ने पर अभी कोई दाली नहीं लिखी।',
  emptyNotebook: 'अभी कोई दाली नहीं लिखी गई।',
  goBack: 'पीछे जाएँ',

  // entries
  addEntry: 'नई दाली',
  editEntry: 'दाली सुधारें',
  name: 'नाम',
  namePh: 'जैसे: रामजी यादव',
  village: 'गाँव',
  villagePh: 'जैसे: मढ़ौरा',
  relation: 'रिश्ता',
  relationPh: 'जैसे: मामा',
  amount: 'रकम',
  date: 'तारीख',
  note: 'नोट',
  notePh: 'जैसे: परिवार सहित',
  writeIt: 'लिख दें',
  save: 'सेव करें',
  cancel: 'रद्द करें',
  delete: 'हटाएँ',
  quickMode: 'फटाफट लिखें',
  quickModeHint: 'एक दाली लिखने के बाद अगली अपने आप खुलेगी',
  nameRequired: 'नाम ज़रूरी है',
  amountRequired: 'रकम ज़रूरी है',
  duplicateWarning: 'ऐसा नाम पहले से है। क्या फिर भी लिखना है?',
  writeAnyway: 'फिर भी लिखें',
  deleteConfirmTitle: 'क्या यह दाली हटानी है?',
  no: 'नहीं',
  yesDelete: 'हाँ, हटाएँ',
  savedToast: 'दाली लिख दी गई ✓',
  updatedToast: 'दाली सुधर गई ✓',
  deletedToast: 'दाली हटा दी गई',
  saveError: 'अभी दाली सेव नहीं हो पाई। कृपया दोबारा कोशिश करें।',

  // search
  searchTitle: 'नाम खोजें',
  searchPlaceholder: 'नाम, गाँव, रिश्ता या रकम लिखें…',
  noResults: 'कुछ नहीं मिला।',
  found: 'मिले',

  // settings
  settings: 'सेटिंग',
  language: 'भाषा',
  hindi: 'हिंदी',
  english: 'English',
  darkMode: 'डार्क मोड',
  darkModeHint: 'रात में देखने के लिए',
  pageAnimation: 'पन्ना पलटने का अंदाज़',
  pinLock: 'पिन लॉक',
  pinLockHint: 'ऐप खोलते समय 4 अंकों का पिन',
  setPin: 'पिन सेट करें',
  removePin: 'पिन हटाएँ',
  enterPin: '4 अंकों का पिन लिखें',
  wrongPin: 'पिन गलत है',
  sort: 'क्रम',
  sortRegister: 'दाली के अनुसार',
  sortName: 'नाम के अनुसार',
  sortAmount: 'रकम के अनुसार',
  sortDate: 'तारीख के अनुसार',
  backupTitle: 'डेटा बैकअप',
  saveBackup: 'डेटा सेव करें (बैकअप)',
  restoreBackup: 'डेटा वापस लाएँ',
  exportCsv: 'Excel / CSV में सेव करें',
  printPdf: 'प्रिंट / PDF',
  confirmRestore: 'बैकअप लाने से अभी का सारा डेटा बदल जाएगा। आगे बढ़ें?',
  restoreOk: 'डेटा वापस आ गया ✓',
  restoreFail: 'यह फ़ाइल सही बैकअप नहीं लगी।',
  backupSaved: 'बैकअप सेव हो गया ✓',
  about: 'बारे में',
  aboutText:
    'दाली रजिस्टर आपकी शादी के हिसाब की डिजिटल कॉपी है। सारा डेटा इसी फोन में सुरक्षित रहता है — इंटरनेट की ज़रूरत नहीं। बैकअप सेव करके दूसरे फोन में ले जा सकते हैं।',
  dataLocalHint: 'आपका हिसाब इसी फोन में रहता है — कोई सर्वर नहीं, कोई लॉगिन नहीं।',

  // delete event
  deleteEventTitle: 'क्या यह रजिस्टर हटाना है?',
  deleteEventWarn: 'इसकी सारी दालियाँ भी हमेशा के लिए मिट जाएँगी।',
  renameEvent: 'नाम बदलें',
  eventDeleted: 'रजिस्टर हटा दिया गया',

  // bottom nav
  navRegister: 'रजिस्टर',
  navSearch: 'खोजें',
  navAdd: 'नई दाली',
  navMore: 'और',

  // lock screen
  lockTitle: 'दाली रजिस्टर लॉक है',
  unlock: 'खोलें',
  forgotPin: 'पिन भूल गए?',
  forgotWarn: 'पिन हटाने के लिए सारा डेटा मिटाना पड़ेगा। क्या सारा हिसाब मिटा दें?',
  resetAll: 'सारा डेटा मिटाएँ',
} as const;

export type TString = keyof typeof hi;

const en: Record<TString, string> = {
  appName: 'Daali Register',
  tagline: 'Your wedding gift register, now in your phone.',
  myRegisters: 'My Registers',
  people: 'people',
  open: 'Open',
  newRegister: 'New Register',
  newRegisterTitle: 'New Wedding / Register',
  createFirst: 'Create your first register',
  noEntriesHome: 'No register yet.',
  eventName: 'Wedding / event name',
  eventNamePh: 'e.g. Brother’s wedding',
  location: 'Location',
  locationPh: 'Village / town',
  createRegister: 'Create Register',
  nameNeeded: 'Please enter a name first',

  daaliRegister: 'Daali Register',
  eventLabel: 'Wedding / Event',
  dateLabel: 'Date',
  villageLabel: 'Village / Place',
  colCr: '#',
  colName: 'Name',
  colVillage: 'Village / Place',
  colRelation: 'Relation',
  colAmount: 'Amount',
  colDate: 'Date',
  page: 'Page',
  totalPeople: 'Total people',
  totalDaali: 'Total gifts',
  pageTotal: 'On this page',
  average: 'Average',
  emptyPage: 'No entries on this page yet.',
  emptyNotebook: 'No entries written yet.',
  goBack: 'Back',

  addEntry: 'New Entry',
  editEntry: 'Edit Entry',
  name: 'Name',
  namePh: 'e.g. Ramji Yadav',
  village: 'Village',
  villagePh: 'e.g. Madhaura',
  relation: 'Relation',
  relationPh: 'e.g. Mama (uncle)',
  amount: 'Amount',
  date: 'Date',
  note: 'Note',
  notePh: 'e.g. with family',
  writeIt: 'Write',
  save: 'Save',
  cancel: 'Cancel',
  delete: 'Delete',
  quickMode: 'Fast entry',
  quickModeHint: 'Next entry opens automatically after saving',
  nameRequired: 'Name is required',
  amountRequired: 'Amount is required',
  duplicateWarning: 'A similar name already exists. Write anyway?',
  writeAnyway: 'Write anyway',
  deleteConfirmTitle: 'Delete this entry?',
  no: 'No',
  yesDelete: 'Yes, delete',
  savedToast: 'Entry written ✓',
  updatedToast: 'Entry updated ✓',
  deletedToast: 'Entry deleted',
  saveError: 'Could not save right now. Please try again.',

  searchTitle: 'Search by name',
  searchPlaceholder: 'Name, village, relation or amount…',
  noResults: 'Nothing found.',
  found: 'found',

  settings: 'Settings',
  language: 'Language',
  hindi: 'हिंदी',
  english: 'English',
  darkMode: 'Dark mode',
  darkModeHint: 'Easier on the eyes at night',
  pageAnimation: 'Page turn animation',
  pinLock: 'PIN lock',
  pinLockHint: '4-digit PIN when opening the app',
  setPin: 'Set PIN',
  removePin: 'Remove PIN',
  enterPin: 'Enter 4-digit PIN',
  wrongPin: 'Wrong PIN',
  sort: 'Order',
  sortRegister: 'Register order',
  sortName: 'By name',
  sortAmount: 'By amount',
  sortDate: 'By date',
  backupTitle: 'Data backup',
  saveBackup: 'Save data (backup)',
  restoreBackup: 'Restore data',
  exportCsv: 'Save as Excel / CSV',
  printPdf: 'Print / PDF',
  confirmRestore: 'Restoring will replace all current data. Continue?',
  restoreOk: 'Data restored ✓',
  restoreFail: 'This does not look like a valid backup file.',
  backupSaved: 'Backup saved ✓',
  about: 'About',
  aboutText:
    'Daali Register is a digital copy of your wedding gift ledger. All data stays on this phone — no internet needed. Save a backup to move it to another phone.',
  dataLocalHint: 'Your data stays on this phone — no server, no login.',

  deleteEventTitle: 'Delete this register?',
  deleteEventWarn: 'All its entries will be deleted permanently.',
  renameEvent: 'Rename',
  eventDeleted: 'Register deleted',

  navRegister: 'Register',
  navSearch: 'Search',
  navAdd: 'New',
  navMore: 'More',

  lockTitle: 'Daali Register is locked',
  unlock: 'Unlock',
  forgotPin: 'Forgot PIN?',
  forgotWarn: 'Removing the PIN requires erasing all data. Erase everything?',
  resetAll: 'Erase all data',
};

const dicts: Record<Language, Record<TString, string>> = { hi, en };

export function makeT(lang: Language) {
  return (key: TString): string => dicts[lang][key] ?? dicts.hi[key] ?? key;
}
