// ─── UI strings — हिंदी (primary) + اردو + English ───────────────────────────
import type { Language } from './types';

const hi = {
  appName: 'दाली रजिस्टर',
  tagline: 'आपकी शादी की दाली अब आपकी मोबाइल कॉपी में।',
  myRegisters: 'मेरी रजिस्टर',
  people: 'लोग',
  open: 'खोलें',
  newRegister: 'नया रजिस्टर',
  newRegisterTitle: 'नई शादी / नया रजिस्टर',
  createFirst: 'अपना पहला रजिस्टर बनाएँ',
  noEntriesHome: 'अभी कोई रजिस्टर नहीं बना।',
  eventName: 'शादी / कार्यक्रम का नाम',
  eventNamePh: 'जैसे: भाई की शादी',
  location: 'स्थान',
  locationPh: 'गाँव / शहर',
  createRegister: 'रजिस्टर बनाएँ',
  nameNeeded: 'पहले नाम लिखें',

  // notebook
  daaliRegister: 'दाली रजिस्टर',
  eventLabel: 'शादी / कार्यक्रम',
  dateLabel: 'तारीख',
  villageLabel: 'गाँव / स्थान',
  colCr: 'क्र.',
  colName: 'नाम',
  colVillage: 'गाँव / स्थान',
  colRelation: 'रिश्ता',
  colAmount: 'रकम / सामान',
  colDate: 'तारीख',
  page: 'पन्ना',
  totalPeople: 'कुल लोग',
  totalDaali: 'कुल दाली',
  pageTotal: 'इस पन्ने में',
  average: 'औसत',
  emptyPage: 'इस पन्ने पर अभी कोई दाली नहीं लिखी।',
  emptyNotebook: 'अभी कोई दाली नहीं लिखी गई।',
  goBack: 'पीछे जाएँ',

  // writing on the lines — no popup, jaise asli copy
  writeHere: 'यहाँ नई दाली लिखें…',
  firstLineHint: 'कॉपी की तरह लिखें — लाइन पर टैप करें, नाम और रकम लिखें, Enter दबाते जाएँ। नेवता/सामान भी लिख सकते हैं।',
  scriptLabel: 'लिखावट',
  scriptHi: 'हिं',
  scriptUr: 'اردو',
  scriptEn: 'Aa',
  scriptHint: 'टाइप करते जाइए — शब्द अपने आप हिंदी/उर्दू में बदल जाएगा',

  // entries
  addEntry: 'नई दाली',
  editEntry: 'दाली सुधारें',
  name: 'नाम',
  namePh: 'नाम लिखें…',
  village: 'गाँव',
  villagePh: 'गाँव',
  relation: 'रिश्ता',
  relationPh: 'रिश्ता',
  amount: 'रकम',
  date: 'तारीख',
  note: 'नोट',
  notePh: 'नोट…',
  writeIt: 'लिख दें',
  save: 'सेव करें',
  cancel: 'रद्द करें',
  delete: 'हटाएँ',
  quickMode: 'फटाफट लिखें',
  quickModeHint: 'एक दाली लिखने के बाद अगली अपने आप खुलेगी',
  nameRequired: 'नाम ज़रूरी है',
  amountRequired: 'रकम या सामान ज़रूरी है',
  cashMode: '₹ नकद',
  itemMode: 'नेवता / सामान',
  itemPh: 'नेवता/सामान लिखें… (मिठाई, कपड़ा, गिफ्ट…)',
  itemCount: 'नेवता/सामान',
  duplicateWarning: 'ऐसा नाम पहले से है। क्या फिर भी लिखना है?',
  writeAnyway: 'फिर भी लिखें',
  deleteConfirmTitle: 'क्या यह दाली हटानी है?',
  no: 'नहीं',
  yesDelete: 'हाँ, हटाएँ',
  savedToast: 'दाली लिख दी गई ✓',
  updatedToast: 'दाली सुधर गई ✓',
  deletedToast: 'दाली हटा दी गई',
  saveError: 'अभी दाली सेव नहीं हो पाई। कृपया दोबारा कोशिश करें।',

  // search
  searchTitle: 'नाम खोजें',
  searchPlaceholder: 'नाम, गाँव, रिश्ता या रकम लिखें…',
  noResults: 'कुछ नहीं मिला।',
  found: 'मिले',

  // settings
  settings: 'सेटिंग',
  language: 'भाषा',
  hindi: 'हिंदी',
  urdu: 'اردو',
  english: 'English',
  darkMode: 'डार्क मोड',
  darkModeHint: 'रात में देखने के लिए',
  pageAnimation: 'पन्ना पलटने का अंदाज़',
  pinLock: 'पिन लॉक',
  pinLockHint: 'ऐप खोलते समय 4 अंकों का पिन',
  setPin: 'पिन सेट करें',
  removePin: 'पिन हटाएँ',
  enterPin: '4 अंकों का पिन लिखें',
  wrongPin: 'पिन गलत है',
  sort: 'क्रम',
  sortRegister: 'दाली के अनुसार',
  sortName: 'नाम के अनुसार',
  sortAmount: 'रकम के अनुसार',
  sortDate: 'तारीख के अनुसार',
  backupTitle: 'डेटा बैकअप',
  saveBackup: 'डेटा सेव करें (बैकअप)',
  restoreBackup: 'डेटा वापस लाएँ',
  exportCsv: 'Excel / CSV में सेव करें',
  printPdf: 'प्रिंट करें',
  pdfDownload: 'PDF डाउनलोड करें',
  pdfMaking: 'PDF बन रही है…',
  pdfDone: 'PDF डाउनलोड हो गई ✓',
  pdfError: 'PDF नहीं बन पाई। फिर कोशिश करें।',
  confirmRestore: 'बैकअप लाने से अभी का सारा डेटा बदल जाएगा। आगे बढ़ें?',
  restoreOk: 'डेटा वापस आ गया ✓',
  restoreFail: 'यह फ़ाइल सही बैकअप नहीं लगी।',
  backupSaved: 'बैकअप सेव हो गया ✓',
  about: 'बारे में',
  aboutText:
    'दाली रजिस्टर आपकी शादी के हिसाब की डिजिटल कॉपी है। सारा डेटा इसी फोन में सुरक्षित रहता है — इंटरनेट की ज़रूरत नहीं। बैकअप सेव करके दूसरे फोन में ले जा सकते हैं।',
  dataLocalHint: 'आपका हिसाब इसी फोन में रहता है — कोई सर्वर नहीं, कोई लॉगिन नहीं।',

  // delete event
  deleteEventTitle: 'क्या यह रजिस्टर हटाना है?',
  deleteEventWarn: 'इसकी सारी दालियाँ भी हमेशा के लिए मिट जाएँगी।',
  renameEvent: 'नाम बदलें',
  eventDeleted: 'रजिस्टर हटा दिया गया',

  // bottom nav
  navRegister: 'रजिस्टर',
  navSearch: 'खोजें',
  navAdd: 'नई दाली',
  navMore: 'और',

  // lock screen
  lockTitle: 'दाली रजिस्टर लॉक है',
  unlock: 'खोलें',
  forgotPin: 'पिन भूल गए?',
  forgotWarn: 'पिन हटाने के लिए सारा डेटा मिटाना पड़ेगा। क्या सारा हिसाब मिटा दें?',
  resetAll: 'सारा डेटा मिटाएँ',

  // history (हिस्ट्री) — har badlav ka record
  viewHistory: 'हिस्ट्री देखें',
  history: 'हिस्ट्री',
  historySub: 'सब बदलाव अपने आप सेव होते हैं — जोड़ना, बदलना, हटाना',
  historyEmpty: 'अभी कोई बदलाव नहीं हुआ है। दाली लिखते ही यहाँ रिकॉर्ड बनेगा।',
  historyCleared: 'हिस्ट्री मिटा दी गई',
  clearHistory: 'हिस्ट्री मिटाएँ',
  clearHistoryConfirm: 'क्या पूरी हिस्ट्री मिटानी है? दालियाँ बनी रहेंगी।',
  today: 'आज',
  yesterday: 'कल',
  actAdd: 'नई दाली लिखी',
  actEdit: 'बदलाव किया',
  actDelete: 'दाली हटाई',
  actRenameEvent: 'रजिस्टर का नाम बदला',
  fName: 'नाम',
  fVillage: 'गाँव',
  fRelation: 'नाता',
  fAmount: 'रकम',
  fItem: 'सामान',
  fDate: 'तारीख',
  fNote: 'नोट',
  fEventName: 'रजिस्टर का नाम',
} as const;

export type TString = keyof typeof hi;

const ur: Record<TString, string> = {
  appName: 'دالی رجسٹر',
  tagline: 'آپ کی شادی کی دالی اب آپ کے موبائل کی کاپی میں۔',
  myRegisters: 'میرے رجسٹر',
  people: 'لوگ',
  open: 'کھولیں',
  newRegister: 'نیا رجسٹر',
  newRegisterTitle: 'نئی شادی / نیا رجسٹر',
  createFirst: 'اپنا پہلا رجسٹر بنائیں',
  noEntriesHome: 'ابھی کوئی رجسٹر نہیں بنا۔',
  eventName: 'شادی / پروگرام کا نام',
  eventNamePh: 'مثلاً: بھائی کی شادی',
  location: 'جگہ',
  locationPh: 'گاؤں / شہر',
  createRegister: 'رجسٹر بنائیں',
  nameNeeded: 'پہلے نام لکھیں',

  daaliRegister: 'دالی رجسٹر',
  eventLabel: 'شادی / پروگرام',
  dateLabel: 'تاریخ',
  villageLabel: 'گاؤں / جگہ',
  colCr: 'نمبر',
  colName: 'نام',
  colVillage: 'گاؤں / جگہ',
  colRelation: 'رشتہ',
  colAmount: 'رقم / سامان',
  colDate: 'تاریخ',
  page: 'صفحہ',
  totalPeople: 'کل لوگ',
  totalDaali: 'کل دالی',
  pageTotal: 'اس صفحے میں',
  average: 'اوسط',
  emptyPage: 'اس صفحے پر ابھی کوئی دالی نہیں لکھی۔',
  emptyNotebook: 'ابھی کوئی دالی نہیں لکھی گئی۔',
  goBack: 'واپس',

  writeHere: 'یہاں نئی دالی لکھیں…',
  firstLineHint: 'کاپی کی طرح لکھیں — لائن پر ٹیپ کریں، نام اور رقم لکھیں، Enter دباتے جائیں۔ نیوتا/سامان بھی لکھ سکتے ہیں۔',
  scriptLabel: 'لکھائی',
  scriptHi: 'हिं',
  scriptUr: 'اردو',
  scriptEn: 'Aa',
  scriptHint: 'ٹائپ کرتے جائیں — لفظ خود بخود ہندی/اردو میں بدل جائے گا',

  addEntry: 'نئی دالی',
  editEntry: 'دالی درست کریں',
  name: 'نام',
  namePh: 'نام لکھیں…',
  village: 'گاؤں',
  villagePh: 'گاؤں',
  relation: 'رشتہ',
  relationPh: 'رشتہ',
  amount: 'رقم',
  date: 'تاریخ',
  note: 'نوٹ',
  notePh: 'نوٹ…',
  writeIt: 'لکھ دیں',
  save: 'سیو کریں',
  cancel: 'منسوخ کریں',
  delete: 'حذف کریں',
  quickMode: 'پھٹافٹ لکھیں',
  quickModeHint: 'ایک دالی لکھنے کے بعد اگلی خود کھل جائے گی',
  nameRequired: 'نام ضروری ہے',
  amountRequired: 'رقم یا سامان ضروری ہے',
  cashMode: '₹ نقد',
  itemMode: 'نیوتا / سامان',
  itemPh: 'نیوتا/سامان لکھیں… (مٹھائی، کپڑا، گفٹ…)',
  itemCount: 'نیوتا/سامان',
  duplicateWarning: 'ایسا نام پہلے سے ہے۔ کیا پھر بھی لکھنا ہے؟',
  writeAnyway: 'پھر بھی لکھیں',
  deleteConfirmTitle: 'کیا یہ دالی حذف کرنی ہے؟',
  no: 'نہیں',
  yesDelete: 'ہاں، حذف کریں',
  savedToast: 'دالی لکھ دی گئی ✓',
  updatedToast: 'دالی درست ہو گئی ✓',
  deletedToast: 'دالی حذف کر دی گئی',
  saveError: 'ابھی دالی سیو نہیں ہو سکی۔ براہ کرم دوبارہ کوشش کریں۔',

  searchTitle: 'نام تلاش کریں',
  searchPlaceholder: 'نام، گاؤں، رشتہ یا رقم لکھیں…',
  noResults: 'کچھ نہیں ملا۔',
  found: 'ملے',

  settings: 'سیٹنگ',
  language: 'زبان',
  hindi: 'ہندی',
  urdu: 'اردو',
  english: 'English',
  darkMode: 'ڈارک موڈ',
  darkModeHint: 'رات میں دیکھنے کے لیے',
  pageAnimation: 'صفحہ پلٹنے کا انداز',
  pinLock: 'پن لاک',
  pinLockHint: 'ایپ کھولتے وقت 4 ہندسوں کا پن',
  setPin: 'پن سیٹ کریں',
  removePin: 'پن ہٹائیں',
  enterPin: '4 ہندسوں کا پن لکھیں',
  wrongPin: 'پن غلط ہے',
  sort: 'ترتیب',
  sortRegister: 'دالی کے مطابق',
  sortName: 'نام کے مطابق',
  sortAmount: 'رقم کے مطابق',
  sortDate: 'تاریخ کے مطابق',
  backupTitle: 'ڈیٹا بیک اپ',
  saveBackup: 'ڈیٹا سیو کریں (بیک اپ)',
  restoreBackup: 'ڈیٹا واپس لائیں',
  exportCsv: 'Excel / CSV میں سیو کریں',
  printPdf: 'پرنٹ کریں',
  pdfDownload: 'PDF ڈاؤن لوڈ کریں',
  pdfMaking: 'PDF بن رہی ہے…',
  pdfDone: 'PDF ڈاؤن لوڈ ہو گئی ✓',
  pdfError: 'PDF نہیں بن سکی۔ دوبارہ کوشش کریں۔',
  confirmRestore: 'بیک اپ لانے سے ابھی کا سارا ڈیٹا بدل جائے گا۔ آگے بڑھیں؟',
  restoreOk: 'ڈیٹا واپس آ گیا ✓',
  restoreFail: 'یہ فائل درست بیک اپ نہیں لگی۔',
  backupSaved: 'بیک اپ سیو ہو گیا ✓',
  about: 'تعارف',
  aboutText:
    'دالی رجسٹر آپ کی شادی کے حساب کی ڈیجیٹل کاپی ہے۔ سارا ڈیٹا اسی فون میں محفوظ رہتا ہے — انٹرنیٹ کی ضرورت نہیں۔ بیک اپ سیو کر کے دوسرے فون میں لے جا سکتے ہیں۔',
  dataLocalHint: 'آپ کا حساب اسی فون میں رہتا ہے — کوئی سرور نہیں، کوئی لاگ ان نہیں۔',

  deleteEventTitle: 'کیا یہ رجسٹر حذف کرنا ہے؟',
  deleteEventWarn: 'اس کی ساری دالیاں بھی ہمیشہ کے لیے مٹ جائیں گی۔',
  renameEvent: 'نام بدلیں',
  eventDeleted: 'رجسٹر حذف کر دیا گیا',

  navRegister: 'رجسٹر',
  navSearch: 'تلاش',
  navAdd: 'نئی دالی',
  navMore: 'مزید',

  lockTitle: 'دالی رجسٹر لاک ہے',
  unlock: 'کھولیں',
  forgotPin: 'پن بھول گئے؟',
  forgotWarn: 'پن ہٹانے کے لیے سارا ڈیٹا مٹانا پڑے گا۔ کیا سارا حساب مٹا دیں؟',
  resetAll: 'سارا ڈیٹا مٹائیں',

  // history
  viewHistory: 'تاریخ دیکھیں',
  history: 'تاریخ',
  historySub: 'سب تبدیلیاں خود بخود محفوظ ہوتی ہیں — لکھنا، بدلنا، مٹانا',
  historyEmpty: 'ابھی کوئی تبدیلی نہیں ہوئی۔ دالی لکھتے ہی یہاں ریکارڈ بنے گا۔',
  historyCleared: 'تاریخ مٹا دی گئی',
  clearHistory: 'تاریخ مٹائیں',
  clearHistoryConfirm: 'کیا پوری تاریخ مٹانی ہے؟ دالیاں باقی رہیں گی۔',
  today: 'آج',
  yesterday: 'کل',
  actAdd: 'نئی دالی لکھی',
  actEdit: 'تبدیلی کی',
  actDelete: 'دالی ہٹائی',
  actRenameEvent: 'رجسٹر کا نام بدلا',
  fName: 'نام',
  fVillage: 'گاؤں',
  fRelation: 'رشتہ',
  fAmount: 'رقم',
  fItem: 'سامان',
  fDate: 'تاریخ',
  fNote: 'نوٹ',
  fEventName: 'رجسٹر کا نام',
};

const en: Record<TString, string> = {
  appName: 'Daali Register',
  tagline: 'Your wedding gift register, now in your phone.',
  myRegisters: 'My Registers',
  people: 'people',
  open: 'Open',
  newRegister: 'New Register',
  newRegisterTitle: 'New Wedding / Register',
  createFirst: 'Create your first register',
  noEntriesHome: 'No register yet.',
  eventName: 'Wedding / event name',
  eventNamePh: 'e.g. Brother’s wedding',
  location: 'Location',
  locationPh: 'Village / town',
  createRegister: 'Create Register',
  nameNeeded: 'Please enter a name first',

  daaliRegister: 'Daali Register',
  eventLabel: 'Wedding / Event',
  dateLabel: 'Date',
  villageLabel: 'Village / Place',
  colCr: '#',
  colName: 'Name',
  colVillage: 'Village / Place',
  colRelation: 'Relation',
  colAmount: 'Amount / Item',
  colDate: 'Date',
  page: 'Page',
  totalPeople: 'Total people',
  totalDaali: 'Total gifts',
  pageTotal: 'On this page',
  average: 'Average',
  emptyPage: 'No entries on this page yet.',
  emptyNotebook: 'No entries written yet.',
  goBack: 'Back',

  writeHere: 'Write next entry…',
  firstLineHint: 'Write like a paper copy — tap a line, write name & amount, press Enter. Gifts/items (nevta) can be written too.',
  scriptLabel: 'Writing script',
  scriptHi: 'हिं',
  scriptUr: 'اردو',
  scriptEn: 'Aa',
  scriptHint: 'Keep typing — words turn into Hindi/Urdu automatically',

  addEntry: 'New Entry',
  editEntry: 'Edit Entry',
  name: 'Name',
  namePh: 'Write name…',
  village: 'Village',
  villagePh: 'Village',
  relation: 'Relation',
  relationPh: 'Relation',
  amount: 'Amount',
  date: 'Date',
  note: 'Note',
  notePh: 'Note…',
  writeIt: 'Write',
  save: 'Save',
  cancel: 'Cancel',
  delete: 'Delete',
  quickMode: 'Fast entry',
  quickModeHint: 'Next entry opens automatically after saving',
  nameRequired: 'Name is required',
  amountRequired: 'Amount or item is required',
  cashMode: '₹ Cash',
  itemMode: 'Nevta / Item',
  itemPh: 'Write gift/item… (sweets, cloth, gift…)',
  itemCount: 'Gifts/items',
  duplicateWarning: 'A similar name already exists. Write anyway?',
  writeAnyway: 'Write anyway',
  deleteConfirmTitle: 'Delete this entry?',
  no: 'No',
  yesDelete: 'Yes, delete',
  savedToast: 'Entry written ✓',
  updatedToast: 'Entry updated ✓',
  deletedToast: 'Entry deleted',
  saveError: 'Could not save right now. Please try again.',

  searchTitle: 'Search by name',
  searchPlaceholder: 'Name, village, relation or amount…',
  noResults: 'Nothing found.',
  found: 'found',

  settings: 'Settings',
  language: 'Language',
  hindi: 'हिंदी',
  urdu: 'اردو',
  english: 'English',
  darkMode: 'Dark mode',
  darkModeHint: 'Easier on the eyes at night',
  pageAnimation: 'Page turn animation',
  pinLock: 'PIN lock',
  pinLockHint: '4-digit PIN when opening the app',
  setPin: 'Set PIN',
  removePin: 'Remove PIN',
  enterPin: 'Enter 4-digit PIN',
  wrongPin: 'Wrong PIN',
  sort: 'Order',
  sortRegister: 'Register order',
  sortName: 'By name',
  sortAmount: 'By amount',
  sortDate: 'By date',
  backupTitle: 'Data backup',
  saveBackup: 'Save data (backup)',
  restoreBackup: 'Restore data',
  exportCsv: 'Save as Excel / CSV',
  printPdf: 'Print',
  pdfDownload: 'Download PDF',
  pdfMaking: 'Making PDF…',
  pdfDone: 'PDF downloaded ✓',
  pdfError: 'Could not make the PDF. Please try again.',
  confirmRestore: 'Restoring will replace all current data. Continue?',
  restoreOk: 'Data restored ✓',
  restoreFail: 'This does not look like a valid backup file.',
  backupSaved: 'Backup saved ✓',
  about: 'About',
  aboutText:
    'Daali Register is a digital copy of your wedding gift ledger. All data stays on this phone — no internet needed. Save a backup to move it to another phone.',
  dataLocalHint: 'Your data stays on this phone — no server, no login.',

  deleteEventTitle: 'Delete this register?',
  deleteEventWarn: 'All its entries will be deleted permanently.',
  renameEvent: 'Rename',
  eventDeleted: 'Register deleted',

  navRegister: 'Register',
  navSearch: 'Search',
  navAdd: 'New',
  navMore: 'More',

  lockTitle: 'Daali Register is locked',
  unlock: 'Unlock',
  forgotPin: 'Forgot PIN?',
  forgotWarn: 'Removing the PIN requires erasing all data. Erase everything?',
  resetAll: 'Erase all data',

  // history
  viewHistory: 'View history',
  history: 'History',
  historySub: 'Every change is saved automatically — add, edit, delete',
  historyEmpty: 'No changes yet. A record will appear here as soon as you write a daali.',
  historyCleared: 'History cleared',
  clearHistory: 'Clear history',
  clearHistoryConfirm: 'Clear the whole history? The daali entries stay.',
  today: 'Today',
  yesterday: 'Yesterday',
  actAdd: 'New daali written',
  actEdit: 'Changed',
  actDelete: 'Daali deleted',
  actRenameEvent: 'Register renamed',
  fName: 'Name',
  fVillage: 'Village',
  fRelation: 'Relation',
  fAmount: 'Amount',
  fItem: 'Item',
  fDate: 'Date',
  fNote: 'Note',
  fEventName: 'Register name',
};

const dicts: Record<Language, Record<TString, string>> = { hi, ur, en };

export function makeT(lang: Language) {
  return (key: TString): string => dicts[lang][key] ?? dicts.hi[key] ?? key;
}
